# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Sandra Alvarez"
email: 'sandruskiag@gmail.com'
description: "I'm a games programmer!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sandruski.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_url: 'https://twitter.com/sandruskiag'
linkedin_url: 'https://www.linkedin.com/in/sandra-alvarez-45453215b/'
section_title: 'Projects'
section_subtitle: 'These are some of the projects I have worked on.'

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate

### Phantom settings
paginate: 10
footer_text: ''
admin_name: 'Sandra Alvarez'
google_analytics: "UA-9999999-99" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
